### ISSUE TITLE
Updated logos in the gh-pages branch, change not visible

### ISSUE THREAD

**Issue by milovanderlinden** [Code-for-All/codeforall.org#12]
I have changed the gh-pages branch; added 2 logos and changed the code slightly that gets the logos. But the change is not visible. Is something wrong or are the pages hosted elsewhere then on github pages?

**Comment by KrzysztofMadejski** [comment]
Fixed here https://github.com/Code-for-All/codeforall.org/commit/89d502e1062937bbca531dd6bc66a17831f04a5a and here https://github.com/Code-for-All/codeforall.org/commit/47e7892c930aabf1835a10491fdb51a874a0518f
