### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by jgroenen** [Code-for-All/codeforall.org#16]
@KrzysztofMadejski what kind of resources are you looking for, and what do you want to do with them?

**Comment by KrzysztofMadejski** [comment]
Well, we have a list here: https://codeforall.org/resources

Basically I want to gather from members actionable playbooks or documentations of case studies. Materials that could support setting up similar initiatives in other countries or be shared How-Tos

**Comment by KrzysztofMadejski** [comment]
@jgroenen Can I close this issue?

**Comment by jgroenen** [comment]
Yes
